# generated by datamodel-codegen:
#   filename:  v1.yaml
#   timestamp: 2026-05-26T13:54:59+00:00

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, PositiveInt, confloat, conint, constr


class Error(BaseModel):
    code: str
    message: str


class ErrorResponse(BaseModel):
    error: Error


class SourceStatus(StrEnum):
    fresh = 'fresh'
    partial = 'partial'
    stale = 'stale'
    blocked = 'blocked'
    unknown = 'unknown'


class Confidence(StrEnum):
    high = 'high'
    medium = 'medium'
    low = 'low'
    blocked = 'blocked'


class SourceType(StrEnum):
    wb_api = 'wb_api'
    wb_excel = 'wb_excel'
    manual = 'manual'
    derived = 'derived'
    mock = 'mock'


class SourceEvidenceItem(BaseModel):
    sourceId: constr(min_length=1)
    sourceType: SourceType
    sourceName: constr(min_length=1)
    lastSyncedAt: AwareDatetime | None
    freshnessTtlMinutes: PositiveInt | None
    fieldsUsed: list[constr(min_length=1)]


class Period(BaseModel):
    dateFrom: date
    dateTo: date


class ReportState(StrEnum):
    operative = 'operative'
    preliminary = 'preliminary'
    final = 'final'
    blocked = 'blocked'


class GroupBy(StrEnum):
    sku = 'sku'
    brand = 'brand'
    manager = 'manager'
    category = 'category'
    status = 'status'
    warehouse = 'warehouse'
    campaign = 'campaign'


class Totals(BaseModel):
    revenueKopecks: conint(ge=0) | None
    netProfitKopecks: int | None
    marginPct: float | None
    sourceStatus: SourceStatus
    confidence: Confidence


class Row(BaseModel):
    rowId: constr(min_length=1)
    label: constr(min_length=1)
    brandId: str | None
    managerId: str | None
    skuId: str | None
    revenueKopecks: conint(ge=0) | None
    cogsKopecks: conint(ge=0) | None
    commissionKopecks: conint(ge=0) | None
    logisticsKopecks: conint(ge=0) | None
    storageKopecks: conint(ge=0) | None
    adSpendKopecks: conint(ge=0) | None
    taxKopecks: conint(ge=0) | None
    overheadKopecks: conint(ge=0) | None
    netProfitKopecks: int | None
    marginPct: float | None
    sourceStatus: SourceStatus
    confidence: Confidence


class FieldMappingItem(BaseModel):
    metricId: constr(min_length=1)
    metricLabel: constr(min_length=1)
    sourceId: constr(min_length=1)
    sourceField: constr(min_length=1) | None
    formula: constr(min_length=1)
    fallback: constr(min_length=1) | None
    blockerIds: list[constr(min_length=1)]


class AllocationBase(StrEnum):
    sku = 'sku'
    brand = 'brand'
    manager = 'manager'
    marketplace = 'marketplace'
    manual = 'manual'
    unknown = 'unknown'


class ManualCost(BaseModel):
    costId: constr(min_length=1)
    label: constr(min_length=1)
    amountKopecks: conint(ge=0) | None
    allocationBase: AllocationBase
    sourceStatus: SourceStatus
    blockerIds: list[constr(min_length=1)]


class DayAllocation(BaseModel):
    allocationDateField: constr(min_length=1) | None
    expenseDateField: constr(min_length=1) | None
    rule: constr(min_length=1)
    sourceStatus: SourceStatus
    blockerIds: list[constr(min_length=1)]


class PnlReportResponse(BaseModel):
    sourceStatus: SourceStatus
    confidence: Confidence
    blockerIds: list[constr(min_length=1)]
    sourceEvidence: list[SourceEvidenceItem]
    calculatedAt: AwareDatetime
    period: Period
    reportState: ReportState
    groupBy: GroupBy
    totals: Totals
    rows: list[Row]
    fieldMapping: list[FieldMappingItem]
    manualCosts: list[ManualCost]
    dayAllocation: DayAllocation


class SourceEvidenceItem1(BaseModel):
    sourceId: constr(min_length=1)
    sourceType: SourceType
    sourceName: constr(min_length=1)
    lastSyncedAt: AwareDatetime | None
    freshnessTtlMinutes: PositiveInt | None
    fieldsUsed: list[constr(min_length=1)]


class Totals1(BaseModel):
    adSpendKopecks: conint(ge=0) | None
    impressions: conint(ge=0) | None
    clicks: conint(ge=0) | None
    cartAdds: conint(ge=0) | None
    ordersCount: conint(ge=0) | None
    ordersKopecks: conint(ge=0) | None
    drrPct: float | None
    romiPct: float | None
    roiPct: float | None


class AttributionLevel(StrEnum):
    exact_sku = 'exact_sku'
    campaign_sku = 'campaign_sku'
    campaign_only = 'campaign_only'
    unknown = 'unknown'


class Row1(BaseModel):
    rowId: constr(min_length=1)
    campaignId: str | None
    skuId: str | None
    brandId: str | None
    managerId: str | None
    adSpendKopecks: conint(ge=0) | None
    impressions: conint(ge=0) | None
    clicks: conint(ge=0) | None
    cartAdds: conint(ge=0) | None
    ordersCount: conint(ge=0) | None
    ordersKopecks: conint(ge=0) | None
    drrPct: float | None
    romiPct: float | None
    roiPct: float | None
    attributionLevel: AttributionLevel
    confidence: Confidence


class AllowedSkuLevel(StrEnum):
    exact_sku = 'exact_sku'
    campaign_sku = 'campaign_sku'
    campaign_only = 'campaign_only'
    unknown = 'unknown'


class AttributionPolicy(BaseModel):
    allowedSkuLevels: list[AllowedSkuLevel]
    campaignOnlyCanAllocateToSkuPnl: bool
    notes: list[constr(min_length=1)]


class AdsPerformanceResponse(BaseModel):
    sourceStatus: SourceStatus
    confidence: Confidence
    blockerIds: list[constr(min_length=1)]
    sourceEvidence: list[SourceEvidenceItem1]
    calculatedAt: AwareDatetime
    period: Period
    groupBy: GroupBy
    totals: Totals1
    rows: list[Row1]
    attributionPolicy: AttributionPolicy


class SourceEvidenceItem2(BaseModel):
    sourceId: constr(min_length=1)
    sourceType: SourceType
    sourceName: constr(min_length=1)
    lastSyncedAt: AwareDatetime | None
    freshnessTtlMinutes: PositiveInt | None
    fieldsUsed: list[constr(min_length=1)]


class Row2(BaseModel):
    rowId: constr(min_length=1)
    label: constr(min_length=1)
    warehouseId: conint(ge=0) | None = None
    warehouseName: str | None = None
    warehouses: list[dict[str, Any]] = []
    skuId: str | None
    brandId: str | None
    managerId: str | None
    adSpendKopecks: conint(ge=0) | None
    drrPct: float | None
    roiPct: float | None
    marginPct: float | None
    sourceStatus: SourceStatus
    confidence: Confidence


class AdsSourceStatus(StrEnum):
    fresh = 'fresh'
    partial = 'partial'
    stale = 'stale'
    blocked = 'blocked'
    unknown = 'unknown'


class RnpReportResponse(BaseModel):
    sourceStatus: SourceStatus
    confidence: Confidence
    blockerIds: list[constr(min_length=1)]
    sourceEvidence: list[SourceEvidenceItem2]
    calculatedAt: AwareDatetime
    period: Period
    groupBy: GroupBy
    rows: list[Row2]
    adSpendKopecks: conint(ge=0) | None
    drrPct: float | None
    formulaNotes: list[constr(min_length=1)]
    adsSourceStatus: AdsSourceStatus


class SourceEvidenceItem3(BaseModel):
    sourceId: constr(min_length=1)
    sourceType: SourceType
    sourceName: constr(min_length=1)
    lastSyncedAt: AwareDatetime | None
    freshnessTtlMinutes: PositiveInt | None
    fieldsUsed: list[constr(min_length=1)]


class FilteredSummary(BaseModel):
    filterHash: constr(min_length=1)
    skuCount: conint(ge=0)
    locomotiveCount: conint(ge=0) | None
    ordersCount: conint(ge=0) | None
    ordersKopecks: conint(ge=0) | None
    profitKopecks: int | None
    marginPct: float | None
    adSpendKopecks: conint(ge=0) | None
    sourceStatus: SourceStatus
    confidence: Confidence


class AbcReportResponse(BaseModel):
    sourceStatus: SourceStatus
    confidence: Confidence
    blockerIds: list[constr(min_length=1)]
    sourceEvidence: list[SourceEvidenceItem3]
    calculatedAt: AwareDatetime
    period: Period
    filteredSummary: FilteredSummary
    rows: list[Any]


class SppSnapshot(BaseModel):
    sourceStatus: SourceStatus
    sppPct: confloat(ge=0.0, le=100.0) | None
    buyerPriceKopecks: PositiveInt | None
    capturedAt: AwareDatetime | None
    blockerIds: list[constr(min_length=1)]


class FreezeState(StrEnum):
    none = 'none'
    frozen = 'frozen'
    requires_review = 'requires_review'
    source_blocked = 'source_blocked'


class Type(StrEnum):
    stock_jump = 'stock_jump'
    spp_jump = 'spp_jump'
    cogs_jump = 'cogs_jump'
    seller_price_jump = 'seller_price_jump'
    source_stale = 'source_stale'


class Severity(StrEnum):
    info = 'info'
    warning = 'warning'
    blocker = 'blocker'


class GuardTrigger(BaseModel):
    type: Type
    severity: Severity
    observedValue: float | str | None
    previousValue: float | str | None
    threshold: float | str | None
    message: constr(min_length=1)


class SourceEvidenceItem4(BaseModel):
    sourceId: constr(min_length=1)
    sourceType: SourceType
    sourceName: constr(min_length=1)
    lastSyncedAt: AwareDatetime | None
    freshnessTtlMinutes: PositiveInt | None
    fieldsUsed: list[constr(min_length=1)]


class PriceGuardResponse(BaseModel):
    articleId: constr(min_length=1)
    currentPriceKopecks: PositiveInt | None
    buyerPriceKopecks: PositiveInt | None
    sppSnapshot: SppSnapshot | None
    recommendedSellerPriceKopecks: PositiveInt | None
    lastKnownGoodPriceKopecks: PositiveInt | None
    canApply: bool
    blockedReason: str | None
    freezeState: FreezeState
    guardTriggers: list[GuardTrigger]
    sourceEvidence: list[SourceEvidenceItem4]
    blockerIds: list[constr(min_length=1)]


class ApprovalState(StrEnum):
    not_required = 'not_required'
    required = 'required'
    approved = 'approved'
    rejected = 'rejected'
    expired = 'expired'


class SendState(StrEnum):
    draft_only = 'draft_only'
    ready_to_send = 'ready_to_send'
    sent = 'sent'
    blocked = 'blocked'


class CacheMetrics(BaseModel):
    cachedTokens: conint(ge=0)
    hitRatePct: confloat(ge=0.0, le=100.0)


class AuditEvidenceItem(BaseModel):
    sourceId: constr(min_length=1)
    sourceType: SourceType
    sourceName: constr(min_length=1)
    lastSyncedAt: AwareDatetime | None
    freshnessTtlMinutes: PositiveInt | None
    fieldsUsed: list[constr(min_length=1)]


class AiReviewApproval(BaseModel):
    reviewId: constr(min_length=1)
    rating: conint(ge=1, le=5)
    draftId: str | None
    approvalState: ApprovalState
    approvalActorId: constr(min_length=1) | None
    approvedAt: AwareDatetime | None
    externalSendAllowed: bool
    sendState: SendState
    brandVoiceId: str | None
    promptTraceId: str | None
    cacheMetrics: CacheMetrics | None
    auditEvidence: list[AuditEvidenceItem]
