from __future__ import annotations

from pathlib import Path
import py_compile


def test_openapi_generated_models_are_present_and_compilable():
    model_file = Path("app/contracts/vella_wb_19_05_generated.py")
    assert model_file.exists()

    text = model_file.read_text(encoding="utf-8")
    assert "generated by datamodel-codegen" in text
    assert "filename:  v1.yaml" in text

    py_compile.compile(str(model_file), doraise=True)
